version: "3.9"

services:
  frontend:
    image: hardik4002/frontend:1.1.1
    ports:
      - target: 80
        published: 80
        protocol: tcp
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - backend

  mysql_db_app:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - mysql-data-app:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=todo
    networks:
      - backend
  app:
    image: hardik4002/backend:1.2.0   # <<--- must be pushed to registry
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    depends_on:
      - mysql_db_app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db_app/todo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpass
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 5
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - backend

networks:
  backend:
    driver: overlay
volumes:
  mysql-data-app:
