version: "3.9"

services:
  app:
    image: hardik4002/todo-1.0.0   # <<--- must be pushed to registry
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 5
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- --timeout=2 http://localhost:8082/actuator/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - backend

networks:
  backend:
    driver: overlay
